Fix compilation with old clang
	clang++ -I/usr/local/include -O3 -pedantic -std=c++2a -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -frelaxed-template-template-args -Wno-ambiguous-reversed-operator -MD -MP -MF .input_handler.opt.d -c -o .input_handler.opt.o input_handler.cc
	input_handler.cc:1476:16: error: alias template 'ConstArrayView' requires template arguments; argument deduction only allowed for class templates
	        insert(ConstArrayView{content});
	               ^
	./array_view.hh:72:1: note: template is declared here
	using ConstArrayView = ArrayView<const T>;
	^
	input_handler.cc:1522:16: error: alias template 'ConstArrayView' requires template arguments; argument deduction only allowed for class templates
	        insert(ConstArrayView{str});
	               ^
	./array_view.hh:72:1: note: template is declared here
	using ConstArrayView = ArrayView<const T>;
	^
	clang++ -I/usr/local/include -O3 -pedantic -std=c++2a -g -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-address -frelaxed-template-template-args -Wno-ambiguous-reversed-operator -MD -MP -MF .insert_completer.opt.d -c -o .insert_completer.opt.o insert_completer.cc
	2 errors generated.